// SPDX-FileCopyrightText: 2026 Veydan Project
// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1

//! Bilingual demo catalog (EN / RU). Same entity ids; locale picks labels and note bodies.

#[derive(Clone)]
pub struct DemoPack {
    pub default_workspace_name: &'static str,
    pub default_columns: Vec<DemoColumn>,
    pub workspaces: Vec<DemoWorkspace>,
    pub proxies: Vec<DemoProxy>,
    pub profiles: Vec<DemoProfile>,
    pub totp: Vec<DemoTotp>,
    pub passwords: Vec<DemoPassword>,
    #[cfg(desktop)]
    pub ssh_keys: Vec<DemoSshKey>,
    #[cfg(desktop)]
    pub ssh_connections: Vec<DemoSshConn>,
    pub folders: Vec<DemoFolder>,
    pub tags: Vec<DemoTag>,
    pub notes: Vec<DemoNote>,
    pub smart_views: Vec<DemoSmartView>,
    #[cfg(desktop)]
    pub capture_rules: Vec<DemoCapture>,
}

#[derive(Clone)]
pub struct DemoColumn {
    pub name: &'static str,
    pub tag_name: &'static str,
    pub color: &'static str,
}

#[derive(Clone)]
pub struct DemoWorkspace {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub color: &'static str,
    pub icon: &'static str,
    pub columns: Vec<DemoColumn>,
}

#[derive(Clone)]
pub struct DemoProxy {
    pub id: &'static str,
    pub name: &'static str,
    pub proxy_type: &'static str,
    pub host: &'static str,
    pub port: i64,
    pub username: Option<&'static str>,
    pub password: Option<&'static str>,
    pub country: Option<&'static str>,
    pub city: Option<&'static str>,
    pub tags: &'static [&'static str],
}

#[derive(Clone)]
pub struct DemoProfile {
    pub id: &'static str,
    pub name: &'static str,
    pub workspace_id: &'static str,
    pub proxy_id: Option<&'static str>,
    pub fingerprint_preset: &'static str,
    pub locale: &'static str,
    pub languages: &'static str,
    pub timezone: Option<&'static str>,
    pub notes: Option<&'static str>,
    pub tags: &'static [&'static str],
    pub kanban_status: &'static str,
    pub kanban_order: i64,
}

#[derive(Clone)]
pub struct DemoTotp {
    pub id: &'static str,
    pub name: &'static str,
    pub issuer: &'static str,
    pub secret: &'static str,
    pub tags: &'static [&'static str],
}

#[derive(Clone)]
pub struct DemoPassword {
    pub id: &'static str,
    pub title: &'static str,
    pub username: &'static str,
    pub url: &'static str,
    pub password: &'static str,
    pub note: Option<&'static str>,
    pub totp_ids: &'static [&'static str],
    pub tags: &'static [&'static str],
    /// Note titles in this locale. Stored as `note:{id}` on the password, not on the note.
    pub note_titles: &'static [&'static str],
}

#[cfg(desktop)]
#[derive(Clone)]
pub struct DemoSshKey {
    pub id: &'static str,
    pub name: &'static str,
    pub algorithm: &'static str,
}

#[cfg(desktop)]
#[derive(Clone)]
pub struct DemoSshConn {
    pub id: &'static str,
    pub name: &'static str,
    pub host: &'static str,
    pub port: i64,
    pub username: &'static str,
    pub auth_type: &'static str,
    pub password: Option<&'static str>,
    pub ssh_key_id: Option<&'static str>,
    pub requires_2fa: bool,
    pub totp_entry_id: Option<&'static str>,
    pub proxy_id: Option<&'static str>,
    pub workspace_ids: &'static [&'static str],
    pub profile_ids: &'static [&'static str],
}

#[derive(Clone)]
pub struct DemoFolder {
    pub id: &'static str,
    pub name: &'static str,
    pub parent_id: Option<&'static str>,
    pub color: &'static str,
}

#[derive(Clone)]
pub struct DemoTag {
    pub id: &'static str,
    pub name: &'static str,
    pub color: &'static str,
}

#[derive(Clone)]
pub struct DemoNote {
    pub title: &'static str,
    pub content: &'static str,
    pub tags: &'static [&'static str],
    pub folder_id: Option<&'static str>,
    pub bindings: &'static [&'static str],
    pub pinned: bool,
    pub archived: bool,
    pub deleted: bool,
}

#[derive(Clone, Copy)]
pub enum SmartKind {
    OpenTasks,
    Pinned,
    Recent7d,
    HasAttachments,
}

#[derive(Clone)]
pub struct DemoSmartView {
    pub name: &'static str,
    pub color: &'static str,
    pub kind: SmartKind,
}

#[cfg(desktop)]
#[derive(Clone)]
pub struct DemoCapture {
    pub domain: &'static str,
    pub folder_id: &'static str,
    pub tags: &'static [&'static str],
}

fn t(ru: bool, en: &'static str, ru_s: &'static str) -> &'static str {
    if ru {
        ru_s
    } else {
        en
    }
}

/// Build the demo pack for `ru` or `en` (anything else → en).
pub fn pack(locale: &str) -> DemoPack {
    let ru = locale.eq_ignore_ascii_case("ru");
    DemoPack {
        default_workspace_name: t(ru, "Personal", "Личное"),
        default_columns: vec![
            DemoColumn {
                name: t(ru, "Inbox", "Inbox"),
                tag_name: "inbox",
                color: "#94a3b8",
            },
            DemoColumn {
                name: t(ru, "Active", "В работе"),
                tag_name: "active",
                color: "#3b82f6",
            },
            DemoColumn {
                name: t(ru, "Done", "Готово"),
                tag_name: "done",
                color: "#22c55e",
            },
        ],
        workspaces: workspaces(ru),
        proxies: proxies(),
        profiles: profiles(ru),
        totp: totp_entries(),
        passwords: passwords(ru),
        #[cfg(desktop)]
        ssh_keys: ssh_keys(),
        #[cfg(desktop)]
        ssh_connections: ssh_connections(),
        folders: folders(ru),
        tags: tags(),
        notes: notes(ru),
        smart_views: smart_views(ru),
        #[cfg(desktop)]
        capture_rules: capture_rules(),
    }
}

fn workspaces(ru: bool) -> Vec<DemoWorkspace> {
    vec![
        DemoWorkspace {
            id: "demo-ws-smm",
            name: "SMM",
            description: t(ru, "Social media accounts", "Аккаунты соцсетей"),
            color: "#ec4899",
            icon: "megaphone",
            columns: vec![
                DemoColumn {
                    name: t(ru, "Ideas", "Идеи"),
                    tag_name: "ideas",
                    color: "#f9a8d4",
                },
                DemoColumn {
                    name: t(ru, "In progress", "В работе"),
                    tag_name: "in_progress",
                    color: "#ec4899",
                },
                DemoColumn {
                    name: t(ru, "Published", "Опубликовано"),
                    tag_name: "published",
                    color: "#22c55e",
                },
            ],
        },
        DemoWorkspace {
            id: "demo-ws-dev",
            name: t(ru, "Development", "Разработка"),
            description: t(ru, "Product and engineering", "Продукт и разработка"),
            color: "#3b82f6",
            icon: "code",
            columns: vec![
                DemoColumn {
                    name: "Backlog",
                    tag_name: "backlog",
                    color: "#94a3b8",
                },
                DemoColumn {
                    name: "Coding",
                    tag_name: "coding",
                    color: "#3b82f6",
                },
                DemoColumn {
                    name: "Review",
                    tag_name: "review",
                    color: "#f59e0b",
                },
                DemoColumn {
                    name: "Done",
                    tag_name: "done_dev",
                    color: "#22c55e",
                },
            ],
        },
        DemoWorkspace {
            id: "demo-ws-devops",
            name: "DevOps",
            description: t(ru, "Infrastructure and releases", "Инфраструктура и релизы"),
            color: "#10b981",
            icon: "server",
            columns: vec![
                DemoColumn {
                    name: "Plan",
                    tag_name: "plan",
                    color: "#94a3b8",
                },
                DemoColumn {
                    name: "Deploy",
                    tag_name: "deploy",
                    color: "#10b981",
                },
                DemoColumn {
                    name: "Monitor",
                    tag_name: "monitor",
                    color: "#06b6d4",
                },
            ],
        },
        DemoWorkspace {
            id: "demo-ws-biz",
            name: t(ru, "Business", "Бизнес"),
            description: t(ru, "Deals and partners", "Сделки и партнёры"),
            color: "#f59e0b",
            icon: "briefcase",
            columns: vec![
                DemoColumn {
                    name: "Lead",
                    tag_name: "lead",
                    color: "#94a3b8",
                },
                DemoColumn {
                    name: t(ru, "Negotiation", "Переговоры"),
                    tag_name: "negotiation",
                    color: "#f59e0b",
                },
                DemoColumn {
                    name: "Closed",
                    tag_name: "closed",
                    color: "#22c55e",
                },
            ],
        },
    ]
}

fn proxies() -> Vec<DemoProxy> {
    vec![
        DemoProxy {
            id: "demo-px-de",
            name: "DE Residential SOCKS5",
            proxy_type: "socks5",
            host: "proxy-de.example",
            port: 1080,
            username: Some("demo-de"),
            password: Some("demo-pass-de"),
            country: Some("DE"),
            city: Some("Berlin"),
            tags: &["workspace:demo-ws-devops"],
        },
        DemoProxy {
            id: "demo-px-us",
            name: "US Datacenter HTTP",
            proxy_type: "http",
            host: "proxy-us.example",
            port: 8080,
            username: Some("demo-us"),
            password: Some("demo-pass-us"),
            country: Some("US"),
            city: Some("New York"),
            tags: &["workspace:demo-ws-smm"],
        },
        DemoProxy {
            id: "demo-px-nl",
            name: "NL HTTPS Mobile",
            proxy_type: "https",
            host: "proxy-nl.example",
            port: 443,
            username: Some("demo-nl"),
            password: Some("demo-pass-nl"),
            country: Some("NL"),
            city: Some("Amsterdam"),
            tags: &["workspace:demo-ws-smm"],
        },
        DemoProxy {
            id: "demo-px-sg",
            name: "SG Office HTTP",
            proxy_type: "http",
            host: "proxy-sg.example",
            port: 3128,
            username: Some("demo-sg"),
            password: Some("demo-pass-sg"),
            country: Some("SG"),
            city: Some("Singapore"),
            tags: &["workspace:demo-ws-biz"],
        },
        DemoProxy {
            id: "demo-px-home",
            name: "Home SOCKS5",
            proxy_type: "socks5",
            host: "127.0.0.1",
            port: 9050,
            username: None,
            password: None,
            country: None,
            city: None,
            tags: &["workspace:default"],
        },
        DemoProxy {
            id: "demo-px-jump",
            name: "Jump SSH Bastion",
            proxy_type: "ssh",
            host: "bastion.example",
            port: 22,
            username: Some("jump"),
            password: Some("demo-pass-jump"),
            country: Some("DE"),
            city: Some("Falkenstein"),
            tags: &["workspace:demo-ws-devops"],
        },
        DemoProxy {
            id: "demo-px-uk",
            name: "UK Socks Marketing",
            proxy_type: "socks5",
            host: "proxy-uk.example",
            port: 1080,
            username: Some("demo-uk"),
            password: Some("demo-pass-uk"),
            country: Some("GB"),
            city: Some("London"),
            tags: &["workspace:demo-ws-smm"],
        },
        DemoProxy {
            id: "demo-px-fail",
            name: "Fail Check Demo",
            proxy_type: "http",
            host: "dead.proxy.invalid",
            port: 9999,
            username: Some("none"),
            password: Some("none"),
            country: None,
            city: None,
            tags: &[],
        },
    ]
}

fn profiles(ru: bool) -> Vec<DemoProfile> {
    vec![
        DemoProfile {
            id: "demo-pr-bank",
            name: t(ru, "Banking", "Банк"),
            workspace_id: "default",
            proxy_id: Some("demo-px-home"),
            fingerprint_preset: "win11",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("Europe/Berlin"),
            notes: Some(t(ru, "Personal banking only", "Только личный банк")),
            tags: &["active"],
            kanban_status: "active",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-shop",
            name: t(ru, "Shopping", "Покупки"),
            workspace_id: "default",
            proxy_id: None,
            fingerprint_preset: "macos",
            locale: "en-GB",
            languages: "en-GB,en",
            timezone: Some("Europe/London"),
            notes: None,
            tags: &["inbox"],
            kanban_status: "inbox",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-mail",
            name: t(ru, "Personal Mail", "Личная почта"),
            workspace_id: "default",
            proxy_id: None,
            fingerprint_preset: "linux",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("UTC"),
            notes: None,
            tags: &["done"],
            kanban_status: "done",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-ig",
            name: "Instagram Brand A",
            workspace_id: "demo-ws-smm",
            proxy_id: Some("demo-px-us"),
            fingerprint_preset: "win11",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("America/New_York"),
            notes: Some("client:brand-a"),
            tags: &["in_progress", "client:brand-a"],
            kanban_status: "in_progress",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-tt",
            name: "TikTok Brand A",
            workspace_id: "demo-ws-smm",
            proxy_id: Some("demo-px-nl"),
            fingerprint_preset: "win10",
            locale: "nl-NL",
            languages: "nl-NL,en",
            timezone: Some("Europe/Amsterdam"),
            notes: None,
            tags: &["ideas", "client:brand-a"],
            kanban_status: "ideas",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-fb",
            name: "FB Ads EU",
            workspace_id: "demo-ws-smm",
            proxy_id: Some("demo-px-uk"),
            fingerprint_preset: "macos",
            locale: "en-GB",
            languages: "en-GB,en",
            timezone: Some("Europe/London"),
            notes: None,
            tags: &["published"],
            kanban_status: "published",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-li",
            name: "LinkedIn Outreach",
            workspace_id: "demo-ws-smm",
            proxy_id: Some("demo-px-us"),
            fingerprint_preset: "win11",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("America/Chicago"),
            notes: None,
            tags: &["in_progress"],
            kanban_status: "in_progress",
            kanban_order: 1,
        },
        DemoProfile {
            id: "demo-pr-gh",
            name: "GitHub Work",
            workspace_id: "demo-ws-dev",
            proxy_id: None,
            fingerprint_preset: "linux",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("UTC"),
            notes: Some("env:prod"),
            tags: &["coding", "env:prod"],
            kanban_status: "coding",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-qa",
            name: "Staging QA",
            workspace_id: "demo-ws-dev",
            proxy_id: None,
            fingerprint_preset: "win10",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("UTC"),
            notes: Some("env:staging"),
            tags: &["review", "env:staging"],
            kanban_status: "review",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-docs",
            name: "Docs Browse",
            workspace_id: "demo-ws-dev",
            proxy_id: None,
            fingerprint_preset: "macos",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("America/Los_Angeles"),
            notes: None,
            tags: &["backlog"],
            kanban_status: "backlog",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-aws",
            name: "AWS Console",
            workspace_id: "demo-ws-devops",
            proxy_id: Some("demo-px-de"),
            fingerprint_preset: "linux",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("Europe/Berlin"),
            notes: Some("infra:prod"),
            tags: &["deploy", "infra:prod"],
            kanban_status: "deploy",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-grafana",
            name: "Grafana",
            workspace_id: "demo-ws-devops",
            proxy_id: Some("demo-px-de"),
            fingerprint_preset: "linux",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("UTC"),
            notes: None,
            tags: &["monitor"],
            kanban_status: "monitor",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-crm",
            name: "CRM Client Portal",
            workspace_id: "demo-ws-biz",
            proxy_id: Some("demo-px-sg"),
            fingerprint_preset: "win11",
            locale: "en-SG",
            languages: "en-SG,en",
            timezone: Some("Asia/Singapore"),
            notes: None,
            tags: &["negotiation"],
            kanban_status: "negotiation",
            kanban_order: 0,
        },
        DemoProfile {
            id: "demo-pr-bankbiz",
            name: t(ru, "Bank Biz", "Банк (бизнес)"),
            workspace_id: "demo-ws-biz",
            proxy_id: Some("demo-px-sg"),
            fingerprint_preset: "win11",
            locale: "en-US",
            languages: "en-US,en",
            timezone: Some("Asia/Singapore"),
            notes: None,
            tags: &["lead"],
            kanban_status: "lead",
            kanban_order: 0,
        },
    ]
}

fn totp_entries() -> Vec<DemoTotp> {
    vec![
        DemoTotp {
            id: "demo-totp-gh",
            name: "github-work",
            issuer: "GitHub",
            secret: "JBSWY3DPEHPK3PXP",
            tags: &["profile:demo-pr-gh", "workspace:demo-ws-dev"],
        },
        DemoTotp {
            id: "demo-totp-aws",
            name: "aws-root",
            issuer: "Amazon",
            secret: "HXDMVJECJJWSRB3H",
            tags: &["profile:demo-pr-aws", "workspace:demo-ws-devops"],
        },
        DemoTotp {
            id: "demo-totp-cf",
            name: "cloudflare",
            issuer: "Cloudflare",
            secret: "GEZDGNBVGY3TQOJQ",
            tags: &["workspace:demo-ws-devops"],
        },
        DemoTotp {
            id: "demo-totp-gads",
            name: "google-ads",
            issuer: "Google",
            secret: "MFRGG2LTMVZHG2LH",
            tags: &["profile:demo-pr-fb", "workspace:demo-ws-smm"],
        },
        DemoTotp {
            id: "demo-totp-binance",
            name: "binance",
            issuer: "Binance",
            secret: "NBSWY3DPO5XXE3DE",
            tags: &["workspace:default"],
        },
        DemoTotp {
            id: "demo-totp-tg",
            name: "telegram",
            issuer: "Telegram",
            secret: "KRSXG5DTMVRXEZLU",
            tags: &["workspace:demo-ws-smm"],
        },
        DemoTotp {
            id: "demo-totp-1p",
            name: "1password-bridge",
            issuer: "1Password",
            secret: "MFZWIIDDN5SW4Y3F",
            tags: &["workspace:demo-ws-biz"],
        },
        DemoTotp {
            id: "demo-totp-gl",
            name: "gitlab-ci",
            issuer: "GitLab",
            secret: "ORUGS4ZANFZSAYLO",
            tags: &["workspace:demo-ws-dev"],
        },
        DemoTotp {
            id: "demo-totp-hetzner",
            name: "hetzner",
            issuer: "Hetzner",
            secret: "KRUGS4ZANFZSAYJA",
            tags: &["workspace:demo-ws-devops"],
        },
        DemoTotp {
            id: "demo-totp-bw",
            name: "bitwarden",
            issuer: "Bitwarden",
            secret: "IFBEGRCFIZDUQYLC",
            tags: &["workspace:default"],
        },
        DemoTotp {
            id: "demo-totp-do",
            name: "digitalocean",
            issuer: "DigitalOcean",
            secret: "KRSXG5BAON2HE2LO",
            tags: &["workspace:demo-ws-devops"],
        },
        DemoTotp {
            id: "demo-totp-stripe",
            name: "stripe",
            issuer: "Stripe",
            secret: "MJQXGZJTGIZTILLC",
            tags: &["workspace:demo-ws-biz"],
        },
    ]
}

fn passwords(ru: bool) -> Vec<DemoPassword> {
    vec![
        DemoPassword {
            id: "demo-pw-ig",
            title: "Instagram Brand A",
            username: "brand.a",
            url: "https://instagram.com",
            password: "demo-ig-BrandA",
            note: Some(t(
                ru,
                "Ad account for Brand A. 2FA is the Telegram code.",
                "Рекламный кабинет Brand A. 2FA — код Telegram.",
            )),
            totp_ids: &["demo-totp-tg", "demo-totp-cf"],
            tags: &["profile:demo-pr-ig", "workspace:demo-ws-smm", "client/brand-a", "work/smm"],
            note_titles: if ru {
                &["Бриф клиента Brand A", "Контент-план недели"]
            } else {
                &["Client brief Brand A", "Content plan week"]
            },
        },
        DemoPassword {
            id: "demo-pw-gh",
            title: "GitHub",
            username: "octocat",
            url: "https://github.com",
            password: "demo-gh-work",
            note: Some(t(ru, "Work org login.", "Вход в рабочую организацию.")),
            totp_ids: &["demo-totp-gh"],
            tags: &["profile:demo-pr-gh", "workspace:demo-ws-dev", "work/dev"],
            note_titles: if ru {
                &["Онбординг репо", "ADR auth"]
            } else {
                &["Repo onboarding", "ADR auth"]
            },
        },
        DemoPassword {
            id: "demo-pw-aws",
            title: "AWS root",
            username: "root",
            url: "https://console.aws.amazon.com",
            password: "demo-aws-root",
            note: Some(t(ru, "Root. Prefer IAM.", "Root. Лучше IAM.")),
            totp_ids: &["demo-totp-aws"],
            tags: &["profile:demo-pr-aws", "workspace:demo-ws-devops", "infra/prod"],
            note_titles: if ru { &["Runbook деплоя"] } else { &["Deploy runbook"] },
        },
        DemoPassword {
            id: "demo-pw-cf",
            title: "Cloudflare",
            username: "ops@veydan.test",
            url: "https://dash.cloudflare.com",
            password: "demo-cf-ops",
            note: None,
            totp_ids: &["demo-totp-cf"],
            tags: &["workspace:demo-ws-devops", "infra/prod", "work/devops"],
            note_titles: if ru {
                &["Nginx snippet", "Алерты мониторинга"]
            } else {
                &["Nginx snippet", "Monitoring alerts"]
            },
        },
        DemoPassword {
            id: "demo-pw-stripe",
            title: "Stripe",
            username: "billing@veydan.test",
            url: "https://dashboard.stripe.com",
            password: "demo-stripe-bill",
            note: Some(t(ru, "Billing owner.", "Владелец биллинга.")),
            totp_ids: &["demo-totp-stripe"],
            tags: &["workspace:demo-ws-biz", "work/biz"],
            note_titles: if ru { &["Воронка сделок"] } else { &["Deal pipeline"] },
        },
        DemoPassword {
            id: "demo-pw-bank",
            title: t(ru, "Bank", "Банк"),
            username: "admin@veydan.net",
            url: "https://veydan.net",
            password: "demo-bank-admin",
            note: Some(t(
                ru,
                "Personal banking. Vault lock is demo.",
                "Личный банк. Пароль хранилища — demo.",
            )),
            totp_ids: &[],
            tags: &["profile:demo-pr-bank", "workspace:default", "personal"],
            note_titles: if ru {
                &["Health log", "WiFi дома"]
            } else {
                &["Health log", "WiFi codes home"]
            },
        },
    ]
}

#[cfg(desktop)]
fn ssh_keys() -> Vec<DemoSshKey> {
    vec![
        DemoSshKey {
            id: "demo-key-deploy",
            name: "deploy-ed25519",
            algorithm: "ed25519",
        },
        DemoSshKey {
            id: "demo-key-laptop",
            name: "laptop-rsa",
            algorithm: "rsa",
        },
    ]
}

#[cfg(desktop)]
fn ssh_connections() -> Vec<DemoSshConn> {
    vec![
        DemoSshConn {
            id: "demo-ssh-prod",
            name: "prod-web-01",
            host: "prod.example.com",
            port: 22,
            username: "deploy",
            auth_type: "key",
            password: None,
            ssh_key_id: Some("demo-key-deploy"),
            requires_2fa: true,
            totp_entry_id: Some("demo-totp-hetzner"),
            proxy_id: None,
            workspace_ids: &["demo-ws-devops"],
            profile_ids: &["demo-pr-aws"],
        },
        DemoSshConn {
            id: "demo-ssh-staging",
            name: "staging-api",
            host: "staging.example.com",
            port: 22,
            username: "ubuntu",
            auth_type: "password",
            password: Some("demo-pass-staging"),
            ssh_key_id: None,
            requires_2fa: false,
            totp_entry_id: None,
            proxy_id: None,
            workspace_ids: &["demo-ws-devops"],
            profile_ids: &[],
        },
        DemoSshConn {
            id: "demo-ssh-bastion",
            name: "bastion",
            host: "bastion.example.com",
            port: 22,
            username: "jump",
            auth_type: "key",
            password: None,
            ssh_key_id: Some("demo-key-laptop"),
            requires_2fa: false,
            totp_entry_id: None,
            proxy_id: Some("demo-px-jump"),
            workspace_ids: &["demo-ws-devops"],
            profile_ids: &[],
        },
        DemoSshConn {
            id: "demo-ssh-nas",
            name: "home-nas",
            host: "nas.lan",
            port: 22,
            username: "admin",
            auth_type: "password",
            password: Some("demo-pass-nas"),
            ssh_key_id: None,
            requires_2fa: false,
            totp_entry_id: None,
            proxy_id: None,
            workspace_ids: &["default"],
            profile_ids: &[],
        },
        DemoSshConn {
            id: "demo-ssh-ci",
            name: "ci-runner",
            host: "ci.example.com",
            port: 22,
            username: "runner",
            auth_type: "key",
            password: None,
            ssh_key_id: Some("demo-key-deploy"),
            requires_2fa: false,
            totp_entry_id: None,
            proxy_id: None,
            workspace_ids: &["demo-ws-devops"],
            profile_ids: &["demo-pr-grafana"],
        },
    ]
}

fn folders(ru: bool) -> Vec<DemoFolder> {
    vec![
        DemoFolder {
            id: "demo-folder-templates",
            name: "Templates",
            parent_id: None,
            color: "#8b7bff",
        },
        DemoFolder {
            id: "demo-folder-smm",
            name: "SMM",
            parent_id: None,
            color: "#ec4899",
        },
        DemoFolder {
            id: "demo-folder-smm-content",
            name: t(ru, "Content", "Контент"),
            parent_id: Some("demo-folder-smm"),
            color: "#f9a8d4",
        },
        DemoFolder {
            id: "demo-folder-smm-clients",
            name: t(ru, "Clients", "Клиенты"),
            parent_id: Some("demo-folder-smm"),
            color: "#db2777",
        },
        DemoFolder {
            id: "demo-folder-dev",
            name: t(ru, "Development", "Разработка"),
            parent_id: None,
            color: "#3b82f6",
        },
        DemoFolder {
            id: "demo-folder-dev-arch",
            name: t(ru, "Architecture", "Архитектура"),
            parent_id: Some("demo-folder-dev"),
            color: "#60a5fa",
        },
        DemoFolder {
            id: "demo-folder-dev-snip",
            name: t(ru, "Snippets", "Сниппеты"),
            parent_id: Some("demo-folder-dev"),
            color: "#93c5fd",
        },
        DemoFolder {
            id: "demo-folder-devops",
            name: "DevOps",
            parent_id: None,
            color: "#10b981",
        },
        DemoFolder {
            id: "demo-folder-devops-run",
            name: "Runbooks",
            parent_id: Some("demo-folder-devops"),
            color: "#34d399",
        },
        DemoFolder {
            id: "demo-folder-devops-check",
            name: t(ru, "Checklists", "Чеклисты"),
            parent_id: Some("demo-folder-devops"),
            color: "#6ee7b7",
        },
        DemoFolder {
            id: "demo-folder-biz",
            name: t(ru, "Business", "Бизнес"),
            parent_id: None,
            color: "#f59e0b",
        },
        DemoFolder {
            id: "demo-folder-biz-meet",
            name: t(ru, "Meetings", "Встречи"),
            parent_id: Some("demo-folder-biz"),
            color: "#fbbf24",
        },
        DemoFolder {
            id: "demo-folder-biz-fin",
            name: t(ru, "Finance", "Финансы"),
            parent_id: Some("demo-folder-biz"),
            color: "#fcd34d",
        },
        DemoFolder {
            id: "demo-folder-personal",
            name: t(ru, "Personal", "Личное"),
            parent_id: None,
            color: "#6b7280",
        },
        DemoFolder {
            id: "demo-folder-inbox",
            name: "Inbox",
            parent_id: None,
            color: "#94a3b8",
        },
    ]
}

fn tags() -> Vec<DemoTag> {
    vec![
        DemoTag {
            id: "demo-tag-smm",
            name: "work/smm",
            color: "#ec4899",
        },
        DemoTag {
            id: "demo-tag-dev",
            name: "work/dev",
            color: "#3b82f6",
        },
        DemoTag {
            id: "demo-tag-devops",
            name: "work/devops",
            color: "#10b981",
        },
        DemoTag {
            id: "demo-tag-biz",
            name: "work/biz",
            color: "#f59e0b",
        },
        DemoTag {
            id: "demo-tag-personal",
            name: "personal",
            color: "#6b7280",
        },
        DemoTag {
            id: "demo-tag-todo",
            name: "status/todo",
            color: "#94a3b8",
        },
        DemoTag {
            id: "demo-tag-wip",
            name: "status/wip",
            color: "#3b82f6",
        },
        DemoTag {
            id: "demo-tag-done",
            name: "status/done",
            color: "#22c55e",
        },
        DemoTag {
            id: "demo-tag-brand",
            name: "client/brand-a",
            color: "#db2777",
        },
        DemoTag {
            id: "demo-tag-prod",
            name: "infra/prod",
            color: "#ef4444",
        },
        DemoTag {
            id: "demo-tag-staging",
            name: "infra/staging",
            color: "#f59e0b",
        },
    ]
}

fn smart_views(ru: bool) -> Vec<DemoSmartView> {
    vec![
        DemoSmartView {
            name: t(ru, "Open tasks", "Открытые задачи"),
            color: "#f59e0b",
            kind: SmartKind::OpenTasks,
        },
        DemoSmartView {
            name: t(ru, "Pinned", "Закреплённые"),
            color: "#8b7bff",
            kind: SmartKind::Pinned,
        },
        DemoSmartView {
            name: t(ru, "Recent 7 days", "За 7 дней"),
            color: "#3b82f6",
            kind: SmartKind::Recent7d,
        },
        DemoSmartView {
            name: t(ru, "With attachments", "С вложениями"),
            color: "#10b981",
            kind: SmartKind::HasAttachments,
        },
    ]
}

#[cfg(desktop)]
fn capture_rules() -> Vec<DemoCapture> {
    vec![
        DemoCapture {
            domain: "instagram.com",
            folder_id: "demo-folder-smm-content",
            tags: &["work/smm"],
        },
        DemoCapture {
            domain: "github.com",
            folder_id: "demo-folder-dev",
            tags: &["work/dev"],
        },
    ]
}

fn notes(ru: bool) -> Vec<DemoNote> {
    if ru {
        notes_ru()
    } else {
        notes_en()
    }
}

fn notes_en() -> Vec<DemoNote> {
    vec![
        // Templates first
        DemoNote {
            title: "Meeting template",
            content: "# {{title}}\n\n**Date:** {{date}}\n\n## Attendees\n- \n\n## Agenda\n1. \n\n## Notes\n\n## Action items\n- [ ] \n",
            tags: &[],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Incident template",
            content: "# Incident: {{title}}\n\n**Started:** {{date}}\n**Severity:** SEV-?\n\n## Impact\n\n## Timeline\n\n## Root cause\n\n## Follow-ups\n- [ ] \n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // SMM (7)
        DemoNote {
            title: "Content plan week",
            content: "# Content plan — week\n\n| Day | Channel | Topic |\n|-----|---------|-------|\n| Mon | IG | Product teaser |\n| Wed | TikTok | Behind the scenes |\n| Fri | LinkedIn | Case study |\n\nSee also @@Hashtag set Brand A@@.\n\n- [x] Draft IG carousel\n- [ ] Film TikTok\n- [ ] Schedule LinkedIn\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm", "profile:demo-pr-ig"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Hashtag set Brand A",
            content: "# Hashtags — Brand A\n\nPrimary:\n`#BrandA #NewDrop #MadeForYou`\n\nSecondary:\n`#Lifestyle #DailyInspo #Creators`\n\nAvoid overused tags. Max 12 per post.\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Client brief Brand A",
            content: "# Brief — Brand A Q2\n\n**Goal:** +20% engagement\n**Tone:** warm, practical\n**Must show:** product in real use\n\nDeliverables:\n- 12 Reels\n- 8 carousels\n- 4 LinkedIn posts\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm", "domain:instagram.com"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Reels calendar",
            content: "# Reels calendar\n\n- [ ] Hook tests (3 variants)\n- [ ] Captions in EN + RU\n- [x] Thumbnails batch\n\nProfile: Instagram Brand A.\n",
            tags: &["work/smm", "status/todo"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Competitors watch",
            content: "# Competitors\n\n1. RivalCo — strong Reels cadence\n2. AltBrand — better UGC\n3. NicheLab — weak CTAs\n\nSteal with pride: end-card format from RivalCo.\n",
            tags: &["work/smm"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "UTM scheme",
            content: "# UTM scheme\n\n```\nutm_source=instagram|tiktok|linkedin\nutm_medium=social\nutm_campaign=brand_a_q2\nutm_content={{post_id}}\n```\n\nStore in sheet before publish.\n",
            tags: &["work/smm", "status/done"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Post draft IG",
            content: "# Draft — IG carousel\n\nSlide 1: Problem\nSlide 2: Insight\nSlide 3: Product\nSlide 4: CTA\n\nCaption draft links to @@Content plan week@@.\n\n- [ ] Design pass\n- [ ] Legal check\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig", "domain:instagram.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Dev (7)
        DemoNote {
            title: "ADR auth",
            content: "# ADR: Session auth\n\n## Context\nNeed shared login across desktop and mobile.\n\n## Decision\nCookie + device-bound refresh token.\n\n## Consequences\n- Simpler SSO\n- Must rotate refresh on logout\n\nRelated: @@API contracts@@.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "API contracts",
            content: "# API contracts\n\n`POST /v1/sessions` — create\n`GET /v1/me` — current user\n`DELETE /v1/sessions/:id` — logout\n\nErrors: `401`, `409`, `429`.\n\nImplements @@ADR auth@@.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh", "domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SQL migrate snippet",
            content: "# SQL migrate\n\n```sql\nALTER TABLE accounts ADD COLUMN locale TEXT NOT NULL DEFAULT 'en';\nCREATE INDEX idx_accounts_locale ON accounts(locale);\n```\n\nRun on staging first.\n",
            tags: &["work/dev", "infra/staging"],
            folder_id: Some("demo-folder-dev-snip"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Sprint TODO",
            content: "# Sprint TODO\n\n- [x] Auth ADR merged\n- [ ] Rate limit middleware\n- [ ] Mobile offline queue\n- [ ] E2E smoke for notes\n\nOwner: platform team.\n",
            tags: &["work/dev", "status/todo"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Changelog draft",
            content: "# Changelog\n\n## Unreleased\n- Demo data loader\n- Notes smart views\n\n## 0.9.0\n- SSH key store\n- TOTP vault\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Repo onboarding",
            content: "# Onboarding\n\n1. Install Rust + Node\n2. `pnpm install`\n3. `make dev`\n\nDocs live under `/docs`. Ask in #eng.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Old spike notes",
            content: "# Spike (archived)\n\nTried embedding SQLite in WASM — dropped for size.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        // DevOps (7)
        DemoNote {
            title: "Deploy runbook",
            content: "# Deploy runbook\n\n1. Freeze deploys in Slack\n2. `ssh prod-web-01`\n3. Pull tag, migrate, restart\n4. Check Grafana\n\nRollback: @@Rollback checklist@@.\n",
            tags: &["work/devops", "infra/prod", "status/wip"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops", "profile:demo-pr-aws"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Rollback checklist",
            content: "# Rollback checklist\n\n| Step | Owner | Done |\n|------|-------|------|\n| Revert image | on-call | [ ] |\n| Restore DB snapshot | DBA | [ ] |\n| Verify health | on-call | [ ] |\n| Unfreeze | lead | [ ] |\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops-check"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Nginx snippet",
            content: "# Nginx snippet\n\n```nginx\nlocation /api/ {\n  proxy_pass http://127.0.0.1:8080;\n  proxy_set_header X-Request-Id $request_id;\n}\n```\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Monitoring alerts",
            content: "# Alerts\n\n- `http_5xx > 2%` for 5m → PagerDuty\n- `disk > 85%` → Slack #infra\n- `cert_expiry < 14d` → email\n\nDashboard: Grafana profile.\n",
            tags: &["work/devops", "status/todo"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["profile:demo-pr-grafana"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Capacity notes",
            content: "# Capacity\n\nProd: 3× c6i.large, avg CPU 35%.\nNeed +1 node before Black Friday.\n\n- [ ] Order instance\n- [ ] Update ASG\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SSH inventory",
            content: "# SSH inventory\n\n- `prod-web-01` — key + 2FA\n- `staging-api` — password\n- `bastion` — jump\n- `ci-runner` — deploy key\n\nPasswords are placeholders for the demo.\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Incident postmortem",
            content: "# Postmortem — cache stampede\n\n**Impact:** 12m elevated latency\n**Root cause:** missing lock on warm cache\n**Fix:** singleflight + jitter\n\nFollow-ups tracked in sprint.\n",
            tags: &["work/devops", "status/done"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Biz (6)
        DemoNote {
            title: "Deal pipeline",
            content: "# Pipeline\n\n| Deal | Stage | ARR |\n|------|-------|-----|\n| Northwind | Negotiation | $48k |\n| Contoso | Lead | $12k |\n| Fabrikam | Closed | $90k |\n",
            tags: &["work/biz", "status/wip"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz", "profile:demo-pr-crm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Investor meeting",
            content: "# Investor meeting\n\n**Ask:** seed extension\n**Deck:** pitch one-pager\n\nNotes:\n- Liked retention chart\n- Want clearer CAC\n\n- [ ] Update financials\n- [ ] Send follow-up\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "P and L draft",
            content: "# P&L draft (month)\n\n| Item | Amount |\n|------|--------|\n| Revenue | 42,000 |\n| COGS | 8,500 |\n| OpEx | 21,000 |\n| Net | 12,500 |\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz-fin"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Partner contacts",
            content: "# Partners\n\n- **Ada** — agency lead — ada@example.com\n- **Ben** — reseller — ben@example.com\n- **Cara** — legal — cara@example.com\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Contract checklist",
            content: "# Contract checklist\n\n- [x] NDA signed\n- [ ] MSA reviewed\n- [ ] DPA attached\n- [ ] Invoice schedule\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Pitch one-pager",
            content: "# Pitch one-pager\n\n**Problem:** multi-account chaos\n**Product:** profiles + notes + TOTP + SSH in one vault\n**Moat:** local-first sync\n",
            tags: &["work/biz", "status/done"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        // Personal (5)
        DemoNote {
            title: "Monthly budget",
            content: "# Budget\n\n| Category | Plan |\n|----------|------|\n| Rent | 1200 |\n| Food | 400 |\n| Tools | 80 |\n| Fun | 150 |\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Travel wishlist",
            content: "# Travel wishlist\n\n- Lisbon in spring\n- Tokyo for cherry blossoms\n- Road trip Alps\n\n- [ ] Check flight deals\n",
            tags: &["personal", "status/todo"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Health log",
            content: "# Health log\n\nSleep avg 7h. Gym 3×/week.\n\nNext checkup: dentist.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default", "profile:demo-pr-bank"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "WiFi codes home",
            content: "# Home Wi‑Fi\n\nSSID: `HomeLab`\nPass: `demo-wifi-not-real`\n\nGuest VLAN: `HomeGuest`.\n\nNotes lock and password vault: `demo`.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Reading list",
            content: "# Reading list\n\n- Designing Data-Intensive Applications\n- Staff Engineer\n- The Mom Test\n",
            tags: &["personal", "status/wip"],
            folder_id: Some("demo-folder-personal"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Inbox (2)
        DemoNote {
            title: "Quick capture",
            content: "# Quick capture\n\nIdea: show TOTP badge on kanban cards — already shipped, verify on mobile.\n",
            tags: &["status/todo"],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Feature idea vault search",
            content: "# Idea: vault-wide search\n\nSearch notes + TOTP names + SSH hosts in one box.\n\nTrash this if duplicated.\n",
            tags: &[],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: true,
        },
    ]
}

fn notes_ru() -> Vec<DemoNote> {
    vec![
        DemoNote {
            title: "Шаблон встречи",
            content: "# {{title}}\n\n**Дата:** {{date}}\n\n## Участники\n- \n\n## Повестка\n1. \n\n## Заметки\n\n## Действия\n- [ ] \n",
            tags: &[],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Шаблон инцидента",
            content: "# Инцидент: {{title}}\n\n**Начало:** {{date}}\n**Severity:** SEV-?\n\n## Влияние\n\n## Таймлайн\n\n## Причина\n\n## Follow-up\n- [ ] \n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Контент-план недели",
            content: "# Контент-план — неделя\n\n| День | Канал | Тема |\n|------|-------|------|\n| Пн | IG | Тизер продукта |\n| Ср | TikTok | Закулисье |\n| Пт | LinkedIn | Кейс |\n\nСм. @@Набор хештегов Brand A@@.\n\n- [x] Черновик карусели IG\n- [ ] Снять TikTok\n- [ ] Запланировать LinkedIn\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm", "profile:demo-pr-ig"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Набор хештегов Brand A",
            content: "# Хештеги — Brand A\n\nОсновные:\n`#BrandA #NewDrop #MadeForYou`\n\nДоп.:\n`#Lifestyle #DailyInspo #Creators`\n\nНе больше 12 на пост.\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Бриф клиента Brand A",
            content: "# Бриф — Brand A Q2\n\n**Цель:** +20% engagement\n**Тон:** тёплый, практичный\n**Показывать:** продукт в жизни\n\nDeliverables:\n- 12 Reels\n- 8 каруселей\n- 4 поста LinkedIn\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm", "domain:instagram.com"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Календарь Reels",
            content: "# Календарь Reels\n\n- [ ] Тесты хуков (3 варианта)\n- [ ] Подписи EN + RU\n- [x] Пакет обложек\n\nПрофиль: Instagram Brand A.\n",
            tags: &["work/smm", "status/todo"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Конкуренты",
            content: "# Конкуренты\n\n1. RivalCo — сильные Reels\n2. AltBrand — лучше UGC\n3. NicheLab — слабые CTA\n\nВзять формат end-card у RivalCo.\n",
            tags: &["work/smm"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Схема UTM",
            content: "# Схема UTM\n\n```\nutm_source=instagram|tiktok|linkedin\nutm_medium=social\nutm_campaign=brand_a_q2\nutm_content={{post_id}}\n```\n\nФиксировать в таблице до публикации.\n",
            tags: &["work/smm", "status/done"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Черновик поста IG",
            content: "# Черновик — карусель IG\n\nСлайд 1: Проблема\nСлайд 2: Инсайт\nСлайд 3: Продукт\nСлайд 4: CTA\n\nПодпись → @@Контент-план недели@@.\n\n- [ ] Дизайн\n- [ ] Юр. проверка\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig", "domain:instagram.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "ADR auth",
            content: "# ADR: сессионная auth\n\n## Контекст\nНужен общий логин desktop + mobile.\n\n## Решение\nCookie + refresh, привязанный к устройству.\n\n## Последствия\n- Проще SSO\n- Ротация refresh при logout\n\nСвязано: @@API contracts@@.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "API contracts",
            content: "# API contracts\n\n`POST /v1/sessions` — создать\n`GET /v1/me` — текущий пользователь\n`DELETE /v1/sessions/:id` — выход\n\nОшибки: `401`, `409`, `429`.\n\nРеализует @@ADR auth@@.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh", "domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SQL migrate snippet",
            content: "# SQL migrate\n\n```sql\nALTER TABLE accounts ADD COLUMN locale TEXT NOT NULL DEFAULT 'en';\nCREATE INDEX idx_accounts_locale ON accounts(locale);\n```\n\nСначала на staging.\n",
            tags: &["work/dev", "infra/staging"],
            folder_id: Some("demo-folder-dev-snip"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Sprint TODO",
            content: "# Sprint TODO\n\n- [x] Auth ADR смержен\n- [ ] Rate limit middleware\n- [ ] Offline queue на mobile\n- [ ] E2E smoke для notes\n\nВладелец: platform.\n",
            tags: &["work/dev", "status/todo"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Changelog draft",
            content: "# Changelog\n\n## Unreleased\n- Загрузчик демо-данных\n- Smart views для заметок\n\n## 0.9.0\n- Хранилище SSH-ключей\n- TOTP vault\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Онбординг репо",
            content: "# Онбординг\n\n1. Установить Rust + Node\n2. `pnpm install`\n3. `make dev`\n\nДоки в `/docs`. Вопросы в #eng.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Старый спайк",
            content: "# Спайк (архив)\n\nПробовали SQLite в WASM — отказались из‑за размера.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        DemoNote {
            title: "Runbook деплоя",
            content: "# Runbook деплоя\n\n1. Freeze в Slack\n2. `ssh prod-web-01`\n3. Pull tag, migrate, restart\n4. Проверить Grafana\n\nОткат: @@Чеклист отката@@.\n",
            tags: &["work/devops", "infra/prod", "status/wip"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops", "profile:demo-pr-aws"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Чеклист отката",
            content: "# Чеклист отката\n\n| Шаг | Владелец | Done |\n|-----|----------|------|\n| Откатить image | on-call | [ ] |\n| Снапшот БД | DBA | [ ] |\n| Health-check | on-call | [ ] |\n| Unfreeze | lead | [ ] |\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops-check"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Nginx snippet",
            content: "# Nginx snippet\n\n```nginx\nlocation /api/ {\n  proxy_pass http://127.0.0.1:8080;\n  proxy_set_header X-Request-Id $request_id;\n}\n```\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Алерты мониторинга",
            content: "# Алерты\n\n- `http_5xx > 2%` 5m → PagerDuty\n- `disk > 85%` → Slack #infra\n- `cert_expiry < 14d` → email\n\nДашборд: профиль Grafana.\n",
            tags: &["work/devops", "status/todo"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["profile:demo-pr-grafana"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Заметки по ёмкости",
            content: "# Ёмкость\n\nProd: 3× c6i.large, CPU ~35%.\nНужен +1 узел до Чёрной пятницы.\n\n- [ ] Заказать инстанс\n- [ ] Обновить ASG\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SSH inventory",
            content: "# SSH inventory\n\n- `prod-web-01` — ключ + 2FA\n- `staging-api` — пароль\n- `bastion` — jump\n- `ci-runner` — deploy key\n\nПароли — плейсхолдеры для демо.\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Постмортем инцидента",
            content: "# Постмортем — cache stampede\n\n**Влияние:** 12 мин latency\n**Причина:** нет lock на прогреве кэша\n**Фикс:** singleflight + jitter\n\nFollow-up в спринте.\n",
            tags: &["work/devops", "status/done"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Воронка сделок",
            content: "# Воронка\n\n| Сделка | Этап | ARR |\n|--------|------|-----|\n| Northwind | Переговоры | $48k |\n| Contoso | Lead | $12k |\n| Fabrikam | Closed | $90k |\n",
            tags: &["work/biz", "status/wip"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz", "profile:demo-pr-crm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Встреча с инвестором",
            content: "# Встреча с инвестором\n\n**Ask:** seed extension\n**Deck:** pitch one-pager\n\nЗаметки:\n- Понравился retention\n- Просят яснее CAC\n\n- [ ] Обновить финансы\n- [ ] Follow-up письмо\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Черновик P and L",
            content: "# Черновик P&L (месяц)\n\n| Статья | Сумма |\n|--------|-------|\n| Выручка | 42,000 |\n| COGS | 8,500 |\n| OpEx | 21,000 |\n| Net | 12,500 |\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz-fin"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Контакты партнёров",
            content: "# Партнёры\n\n- **Ada** — agency — ada@example.com\n- **Ben** — reseller — ben@example.com\n- **Cara** — legal — cara@example.com\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Чеклист договора",
            content: "# Чеклист договора\n\n- [x] NDA подписан\n- [ ] MSA на ревью\n- [ ] DPA приложен\n- [ ] График счетов\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Pitch one-pager",
            content: "# Pitch one-pager\n\n**Проблема:** хаос мультиаккаунтов\n**Продукт:** профили + заметки + TOTP + SSH в одном vault\n**Moat:** local-first sync\n",
            tags: &["work/biz", "status/done"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        DemoNote {
            title: "Бюджет месяца",
            content: "# Бюджет\n\n| Категория | План |\n|-----------|------|\n| Аренда | 1200 |\n| Еда | 400 |\n| Инструменты | 80 |\n| Развлечения | 150 |\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Wishlist путешествий",
            content: "# Wishlist путешествий\n\n- Лиссабон весной\n- Токио на сакуру\n- Роудтрип по Альпам\n\n- [ ] Смотреть авиабилеты\n",
            tags: &["personal", "status/todo"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Health log",
            content: "# Health log\n\nСон ~7ч. Зал 3×/нед.\n\nСледующий чекап: стоматолог.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default", "profile:demo-pr-bank"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "WiFi дома",
            content: "# Домашний Wi‑Fi\n\nSSID: `HomeLab`\nPass: `demo-wifi-not-real`\n\nGuest VLAN: `HomeGuest`.\n\nПароль блокировки и хранилища паролей: `demo`.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Список чтения",
            content: "# Список чтения\n\n- Designing Data-Intensive Applications\n- Staff Engineer\n- The Mom Test\n",
            tags: &["personal", "status/wip"],
            folder_id: Some("demo-folder-personal"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Быстрый захват",
            content: "# Быстрый захват\n\nИдея: бейдж TOTP на kanban — уже есть, проверить на mobile.\n",
            tags: &["status/todo"],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Идея поиска по vault",
            content: "# Идея: поиск по vault\n\nИскать заметки + имена TOTP + SSH-хосты в одном поле.\n\nУдалить, если дубль.\n",
            tags: &[],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: true,
        },
    ]
}
